services:
  agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bluesome_container
    restart: unless-stopped
    shm_size: "2gb"
    volumes:
      - hermes_home:/home/hermes

volumes:
  hermes_home:
